name: update japanese-addresses on dispath

on: workflow_dispatch

jobs:
  update_japanese_addresses:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    env:
      RESULT_PATH: prefecture2city2street.pkl
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: create pkl
      run: |
        python scripts/csv_to_dict.py
        mv ${{ env.RESULT_PATH }} japanese_addresses/${{ env.RESULT_PATH }}
    - name: Create commits
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "Add japanese-addresses"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Update japanese-addresses
        labels: update file, automated pr
        body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
        branch: update-japanese-addresses 
        delete-branch: true
        token: ${{ secrets.GITHUB }}
